### ISSUE TITLE
`ariadne blockchain sync <name>` is broken

### ISSUE THREAD

**Issue by plredmond** [input-output-hk/rust-cardano#123]
As of e84810f

It's a runtime error, so perhaps something changed about on-disk formats. I haven't had a chance to look into it yet, but I will after finishing my other work.

## Error for existing blockchain

```sh-session
$ RUST_BACKTRACE=1 ./target/debug/ariadne blockchain sync foo
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Message("missing field `peers`", Some(Pos { marker: Marker { index: 10, line: 2, col: 6 }, path: "." }))', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  10: exe_common::config::net::Config::from_file
             at ./exe-common/src/config.rs:227
  11: ariadne::command::blockchain::net_sync_faster
             at wallet-cli/src/command/blockchain/mod.rs:105
  12: <ariadne::command::blockchain::Blockchain as ariadne::command::HasCommand>::run
             at wallet-cli/src/command/blockchain/mod.rs:274
  13: ariadne::main
             at wallet-cli/src/main.rs:43
  14: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  15: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  16: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  17: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  18: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  19: main
  20: __libc_start_main
  21: _start
             at ../sysdeps/x86_64/start.S:120
```

## Error for new blockchain (repro)

```sh-session
$ RUST_BACKTRACE=1 ./target/debug/ariadne blockchain new --template testnet foo2

$ RUST_BACKTRACE=1 ./target/debug/ariadne blockchain sync foo2
Configured genesis   : b365f1be6863b453f12b93e1810909b10c79a95ee44bf53414888513fe172c90
Configured genesis-1 : c6a004d3d178f600cd8caa10abbebe1549bef878f0665aea2903472d5abf7323
latest known epoch 0 hash=Some(HeaderHash(b365f1be6863b453f12b93e1810909b10c79a95ee44bf53414888513fe172c90))
downloading epoch 0 b365f1be6863b453f12b93e1810909b10c79a95ee44bf53414888513fe172c90
 INFO 2018-05-31T16:51:01Z: exe_common::network::hermes: querying uri: http://hermes.dev.iohkdev.io/foo2/epoch/0
 INFO 2018-05-31T16:51:01Z: exe_common::network::hermes: Downloaded EPOCH in 0sec
thread 'main' panicked at 'no last block found, error.', exe-common/src/network/hermes.rs:79:23
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:397
   6: <exe_common::network::hermes::HermesEndPoint as exe_common::network::api::Api>::fetch_epoch
             at exe-common/src/network/hermes.rs:79
   7: <exe_common::network::peer::Peer as exe_common::network::api::Api>::fetch_epoch
             at exe-common/src/network/peer.rs:44
   8: ariadne::command::blockchain::net_sync_faster
             at wallet-cli/src/command/blockchain/mod.rs:132
   9: <ariadne::command::blockchain::Blockchain as ariadne::command::HasCommand>::run
             at wallet-cli/src/command/blockchain/mod.rs:274
  10: ariadne::main
             at wallet-cli/src/main.rs:43
  11: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start
             at ../sysdeps/x86_64/start.S:120
```

**Comment by NicolasDP** [comment]
I found what is the problem here...

```
 INFO 2018-05-31T18:01:27Z: exe_common::network::hermes: querying uri: http://hermes.dev.iohkdev.io/foo/epoch/0
 INFO 2018-05-31T18:01:27Z: exe_common::network::hermes: Downloaded EPOCH in 0sec
```

we are trying to query hermes with `/foo/epoch/0`. Obviously the blockchain `foo` does not exist on hermes.

The fix should be simple, in the configuration file of the network, instead of having just:

```yml
peers:
  - hermes: "http://hermes.dev.iohkdev.io"
```

we would have

```yml
peers:
  - hermes: "http://hermes.dev.iohkdev.io/testnet"
```

```yml
peers:
  - hermes: "http://hermes.dev.iohkdev.io/mainnet"
```

and in the file `exe-common/src/network/hermes.rs`: we need to update the `uri(&self)` function:

```diff
     pub fn uri(& mut self, path: &str) -> String {
-        format!("{}/{}/{}", self.url, self.blockchain, path)
+        format!("{}/{}", self.url, self.blockchain, path)
     }
```

and in the file `exe-common/src/config.rs`:

```diff
         pub fn testnet() -> Self {
-            peers.push("hermes".to_string(), Peer::http("http://hermes.dev.iohkdev.io".to_string()));
+            peers.push("hermes".to_string(), Peer::http("http://hermes.dev.iohkdev.io/testnet".to_string()));
```

same for `mainnet`.
