### ISSUE TITLE
hermes bug with the testnet template

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/rust-cardano#245]
backtrace:
```
thread '<unnamed>' panicked at 'to get one header at least: ServerError("getheadersFromManyTo returned Nothing, reason: GHFBadInput \"no checkpoints are in the main chain\"")', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
   9: <exe_common::network::native::PeerPool as exe_common::network::api::Api>::get_blocks
  10: hermes::service::refresh_network
  11: hermes::service::start_networks_refreshers::{{closure}}
```

**Comment by vincenthz** [comment]
possible reason testnet has been reset to a new configuration, so that "testnet" doesn't match the known configuration
